# Generated by Django 4.0.1 on 2022-07-26 17:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default=main.models.Order.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
    ]
